# Generated by Django 2.2.5 on 2019-12-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='username1',
        ),
    ]
